### ISSUE TITLE
Opal 4.4.2 can't connect to MySQL 5

### ISSUE THREAD

**Issue by tombisho** [obiba/opal#3727]
**Describe the bug**
The 'docker-compose.yml' file provided in the Opal help results in a connection error for the MySQL database

**To Reproduce**
1. Install Docker and Docker compose
2. Get the docker-compose.yml from the help page:

```
version: '3'
services:
  opal:
    image: obiba/opal:latest
    ports:
      - "8843:8443"
      - "8880:8080"
    links:
      - rock
      - mongo
      - mysqldata
    environment:
      - JAVA_OPTS=-Xms1G -Xmx8G -XX:+UseG1GC
      - OPAL_ADMINISTRATOR_PASSWORD=password
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MYSQLDATA_HOST=mysqldata
      - MYSQLDATA_USER=opal
      - MYSQLDATA_PASSWORD=password
      - ROCK_HOSTS=rock:8085
    volumes:
      - /tmp/opal:/srv
  mongo:
    image: mongo
  mysqldata:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=opal
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=opal
      - MYSQL_PASSWORD=password
  rock:
    image: obiba/rock:latest
```
3. Start docker-compose with the file
4. Go to Admin-databases and the connection to MySQL fails

I have tried various things like trying to modify the docker-compose file to specify the port for Opal and so on without sucess

Checking the container list shows mysql running on 3306.
The connection config is:

`jdbc:mysql://mysqldata:3306/opal`

**Expected behavior**
I expect to be able to connect!

**Error message**
```
ERROR org.obiba.opal.core.service.ProjectsServiceImpl - Datasource Loader 1: loading datasource of project pie failed for database: mysqldb
org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
```

**Desktop (please complete the following information):**
Ubuntu 20.04

**Comment by tombisho** [comment]
I think the simple fix is to change to MySQL 8

```
 mysqldata:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=opal
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=opal
      - MYSQL_PASSWORD=password
```
any reason why that is a bad idea!?
