### ISSUE TITLE
Opal 4.4.2 (Docker image?) needs MySQL URL modification

### ISSUE THREAD

**Issue by tombisho** [obiba/opal#3729]
**Describe the bug**
Can connect to MySQL database, but cannot create a project. It seems like MySQL has stopped like the table definition that Opal is asking to create.

**To Reproduce**
My docker-compose.yml:

```
version: '3'
services:
  opal:
    image: obiba/opal:latest
    ports:
      - "8443:8443"
      - "8880:8080"
    links:
      - rock
      - mysqldata
    environment:
      - JAVA_OPTS=-Xms1G -Xmx8G -XX:+UseG1GC
      - OPAL_ADMINISTRATOR_PASSWORD=password
      - MYSQLDATA_HOST=mysqldata
      - MYSQLDATA_USER=opal
      - MYSQLDATA_PASSWORD=password
      - ROCK_HOSTS=rock:8085
    volumes:
      - /tmp/opal:/srv
  mysqldata:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=opal
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=opal
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
  rock:
    image: obiba/rock:latest
```

**Expected behavior**
Table to be created...

**Screenshots**
```
ERROR org.obiba.opal.core.service.ProjectsServiceImpl - Datasource Loader 2: loading datasource of project b failed for database: mysqldb
org.obiba.magma.MagmaRuntimeException: org.springframework.jdbc.UncategorizedSQLException: ConnectionCallback; uncategorized SQLException for SQL []; SQL state [null]; error code [0]; liquibase.exception.DatabaseException: Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE `opal`.`categories` (`datasource` VARCHAR(255) NOT NULL, `value_table` VARCHAR(255) NOT NULL, `variable` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `missing` BIT(1) NOT NULL, CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (`datasource`, `value_table`, `variable`, `name`))ENGINE=InnoDB]; nested exception is java.sql.SQLException: liquibase.exception.DatabaseException: Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE `opal`.`categories` (`datasource` VARCHAR(255) NOT NULL, `value_table` VARCHAR(255) NOT NULL, `variable` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `missing` BIT(1) NOT NULL, CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (`datasource`, `value_table`, `variable`, `name`))ENGINE=InnoDB]
```

**Comment by ymarcon** [comment]
How do you declare the mysql database in Opal? On my laptop (not docker, but it should work the same), the connection URL is `jdbc:mysql://localhost:3306/opal_data?verifyServerCertificate=false&useSSL=false&serverTimezone=CET`

**Comment by tombisho** [comment]
Ok - switched back to MySQL 5, and used this connection URL:

`jdbc:mysql://mysqldata:3306/opal?verifyServerCertificate=false&useSSL=false&serverTimezone=CET`

Now I can connect and create projects etc. Excellent!

I guess then this links to #3727 which is what drove me to MySQL 8 in the first place

Is there a problem in the Opal Docker image that specifies the connection URL incorrectly? Ie it is missing the `?verifyServerCertificate=false&useSSL=false&serverTimezone=CET` part? And is it bad that in a production system we are not having a secure connection to the database?

**Comment by tombisho** [comment]
The situation:

1. When I do a clean start from nothing, the URL for MySQL does not work out of the box
2. I have to add the ?verify.... part
3. I don't know if this is a problem with Opal the application or the Docker file
4. I suspect the Docker file as this must somehow populate the URL on Opal?

**Comment by ymarcon** [comment]
Yes, the docker env variables are just helpers, it won't make specific settings.
By the way, SQL databases are usually more complex to setup (and have limits, like number of columns), Mongodb is easier and has less limitations.

**Comment by tombisho** [comment]
Yes, I see now that the easy option is to use MongoDB and will likely go down this route 😀 

But will anyone wanting to use MySQL have this problem? I'm trying to understand whether it's Docker specific or not, or if something has changed in Opal.

As part of this I want to make some suggestions to improve the `docker-compose.yml` file provided in the Opal help pages. At the moment, the MySQL part of that doesn't work. I agree one solution would be to take it out! The other thing I am looking at is setting up volumes for the database

**Comment by tombisho** [comment]
For mongodb, it does not look like there are environment variables for a user and password.

I guess this would mean that if someone could access the container, they could access the db. But they would need sudo to access the contain. The same goes for the files stored in a volume.

**Comment by ymarcon** [comment]
You can init mongodb with username/password and db:
https://hub.docker.com/_/mongo/

**Comment by tombisho** [comment]
Great, thank you - are there corresponding env variables in Opal?

**Comment by tombisho** [comment]
I think by my logic above there might actually be no need. It would be useful to get your opinion.

If the database is not protected by a username and password, then a hacker with sudo rights can access the database. They need sudo rights to access the container in the first place, though. But, if they have sudo rights they can interrogate containers and get the passwords anyway, or get them from the docker-compose file.

In a non container setup a username and password are needed because otherwise any user could connect to the database and get the data.

**Comment by ymarcon** [comment]
I just added the `verifyServerCertificate` and `useSSL` parameters to the mysql connection string. And added the `authSource` parameter to the mongodb connection string. Postgresql works out of the box.

There is still this `Specified key was too long` error with most recent mysql server. As the [char set config](https://opaldoc.obiba.org/en/latest/web-user-guide/administration/databases.html#id1) is not exposed by the mysql docker image, Opal should probably include it explicitly on database creation.

**Comment by tombisho** [comment]
Hi Yannick, this is great, thank you very much (especially for adding the mongoDB part in there too). I will give it a go this week.

**Comment by tombisho** [comment]
> As the [char set config](https://opaldoc.obiba.org/en/latest/web-user-guide/administration/databases.html#id1) is not exposed by the mysql docker image, Opal should probably include it explicitly on database creation.

The other option is to include it in a .cnf file?

I was using this:

````
[mysqld]
tls_version=TLSv1.2
character-set-server=utf8
collation-server=utf8_bin
default-storage-engine=INNODB
innodb_file_per_table
````

and then reference it in the compose file like this:
````
  mysqldata:
    image: mysql:5
    volumes:
      - /home/vagrant/prod/custom:/etc/mysql/conf.d
````
