### ISSUE TITLE
rock rserver is not running in OPAL

### ISSUE THREAD

**Issue by gerhardmayer-UKU** [obiba/opal#3740]
Hello,

we have problems to install the rock R server in OPAL.
We use the following docker-compose installation:

```
version: '3.9'
services:
  opal:
    container_name: opal
    image: obiba/opal:4.4
    ports:
      - "443:8443"
      - "1080:8080"
    links:
      - mongo
      - mysqldata
      - rock
    restart: unless-stopped
    depends_on:
      - "rock"
      - "mongo"
      - "mysqldata"
    environment:
      - JAVA_OPTS=-Dhttp.proxyHost=proxy.klinik.uni-ulm.de -Dhttp.proxyPort=8080 -Xms1G -Xmx8G -XX:+UseG1GC
      - OPAL_ADMINISTRATOR_PASSWORD=<My_OPAL_PASSWORD>
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MYSQLDATA_HOST=mysqldata
      - MYSQLDATA_USER=opal
      - MYSQLDATA_PASSWORD=<My_MYSQL_PASSWORD>
      - ROCK_HOSTS=rock:8085
      - http_proxy=http://<proxy-user>:<proxy-password>@proxy.klinik.uni-ulm.de:8080
      - https_proxy=http://<proxy-user>:<proxy-password>@proxy.klinik.uni-ulm.de:8080
    volumes:
      - opal:/srv
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-db:/data/db
  mysqldata:
    container_name: mysqldata
    image: mysql:5.7.38
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=opal
      - MYSQL_ROOT_PASSWORD=<My_ROOT_PASSWORD>
      - MYSQL_USER=opal
      - MYSQL_PASSWORD=<My_MYSQL_PASSWORD>
    volumes:
      - mysql-db:/var/lib/mysql
  rock:
    container_name: rock
    image: obiba/rock:latest
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      - http_proxy=http://<proxy-user>:<proxy-password>@proxy.klinik.uni-ulm.de:8080
      - https_proxy=http://<proxy-user>:<proxy-password>@proxy.klinik.uni-ulm.de:8080
      - ROCK_ADMINISTRATOR_NAME=administrator
      - ROCK_ADMINISTRATOR_PASSWORD=<My_ROCK_PASSWORD>
    volumes:
      - rock:/srv

volumes:
    opal: {}
    mongo-db: {}
    mysql-db: {}
    rock: {}
```

After docker-compose -f opal.yml up -d the following containers are running:
	obiba/opal:4.4
	mysql:5.7.38
	obiba/rock:latest
	mongo:latest

but when I go to the GUI interface, login there and go to the 'Administration' page I get the following error messages:

No R server is running. Some functionalities will not work properly: data import/export using R, data and resource assignment to R server session, reporting etc.
No resource description providers could be identified. You may need to install the resourcer R package.

docker logs -f rock     gives me the following output:
```
[Info] ROCK_HOME=/srv
First run setup...
[Info] Applying config...
[Info] Node properties
[Warn]   No server public address: self-registration not activated
[Warn]   Setting default node id: rserver
[Info]   Setting default node cluster: default
[Info]   Setting empty node tags
[Info] Consul properties
[Info]   No Consul server: self-registration not activated
[Warn]   No Consul token: self-registration not safe
[Info] Opal properties
[Info]   No Opal server: self-registration not activated
[Warn]   No Opal token: self-registration not valid
[Info] R properties
[Info]   No R repositories, setting default
[Info] Users properties
[Info]   No manager configured!
[Info]   No user configured!
JAVA_OPTS=-Xmx2G
ROCK_HOME=/srv
ROCK_DIST=/usr/share/rock
```

What can we do to make the rock R server running?

Best regards,
Gerhard Mayer
